/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvisRouteImport } from './routes/avis'
import { Route as MarqueRouteImport } from './routes/marque'
import { Route as OverlayRouteImport } from './routes/overlay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisRoute = AvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => rootRouteImport,
} as any)
const MarqueRoute = MarqueRouteImport.update({
  id: '/marque',
  path: '/marque',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayRoute = OverlayRouteImport.update({
  id: '/overlay',
  path: '/overlay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avis': typeof AvisRoute
  '/marque': typeof MarqueRoute
  '/overlay': typeof OverlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avis': typeof AvisRoute
  '/marque': typeof MarqueRoute
  '/overlay': typeof OverlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avis': typeof AvisRoute
  '/marque': typeof MarqueRoute
  '/overlay': typeof OverlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/avis' | '/marque' | '/overlay'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/avis' | '/marque' | '/overlay'
  id: '__root__' | '/' | '/avis' | '/marque' | '/overlay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisRoute: typeof AvisRoute
  MarqueRoute: typeof MarqueRoute
  OverlayRoute: typeof OverlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avis': {
      id: '/avis'
      path: '/avis'
      fullPath: '/avis'
      preLoaderRoute: typeof AvisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marque': {
      id: '/marque'
      path: '/marque'
      fullPath: '/marque'
      preLoaderRoute: typeof MarqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay': {
      id: '/overlay'
      path: '/overlay'
      fullPath: '/overlay'
      preLoaderRoute: typeof OverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisRoute: AvisRoute,
  MarqueRoute: MarqueRoute,
  OverlayRoute: OverlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
